### ISSUE TITLE
undefined local variable or method `notification_target' for User

### ISSUE THREAD

**Issue by horacix** [jonhue/notifications-rails#192]
Hi,
I followed the instructions in the readme to add notification-handler to my project. Gem installed correctly, ran the rake command and the db:migration and all well. 
But when I add `notification_target` to my User model, I get the following error when trying to start the development server:
```
 $ rails s
=> Booting Puma
=> Rails 5.2.3 application starting in development
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
        75: from bin/rails:4:in `<main>'
        74: from bin/rails:4:in `require'
        73: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
        72: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
        71: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
        70: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        69: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        68: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        67: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
        66: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
        65: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        64: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:51:in `start'
        63: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
        62: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
        61: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:27:in `app'
        60: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
        59: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        58: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
        57: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
        56: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
        55: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
        54: from config.ru:3:in `block in <main>'
        53: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        52: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        51: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
        50: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
        49: from /home/horacix/git/escroler_webadmin/config/environment.rb:5:in `<top (required)>'
        48: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
        47: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        46: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        45: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        44: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        43: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
        42: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
        41: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        40: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        39: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:415:in `call'
        38: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
        37: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
        36: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        35: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        34: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        33: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        32: from /usr/share/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        31: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        30: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
        29: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
        28: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
        27: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
        26: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
        25: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
        24: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
        23: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
        22: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
        21: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        20: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
        19: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
        18: from /home/horacix/git/escroler_webadmin/config/initializers/rails_admin.rb:12:in `<top (required)>'
        17: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/rails_admin-2.0.0/lib/rails_admin.rb:31:in `config'
        16: from /home/horacix/git/escroler_webadmin/config/initializers/rails_admin.rb:36:in `block in <top (required)>'
        15: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:195:in `const_missing'
        14: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:510:in `load_missing_constant'
        13: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:356:in `require_or_load'
        12: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `load_interlock'
        11: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:13:in `loading'
        10: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
         9: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
         8: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
         7: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:373:in `block in require_or_load'
         6: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:475:in `load_file'
         5: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:661:in `new_constants_in'
         4: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:476:in `block in load_file'
         3: from /home/horacix/.rvm/gems/ruby-2.6.5/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:476:in `load'
         2: from /home/horacix/git/escroler_webadmin/app/models/user.rb:1:in `<top (required)>'
         1: from /home/horacix/git/escroler_webadmin/app/models/user.rb:2:in `<class:User>'
/home/horacix/.rvm/gems/ruby-2.6.5/gems/activerecord-5.2.3/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined local variable or method `notification_target' for User (call 'User.connection' to establish a connection):Class (NameError)
```

**Comment by jonhue** [comment]
Add `require 'notification-handler' to the top of your file or mention the gem in your Gemfile.

**Comment by bluciam** [comment]
I had the same issue: the `User` model is being loaded in the initializers. The `require` statement did not work. I had to include the concern  instead.
```
include NotificationHandler::Target
```
